ADAFRUIT_IO:
  ADAFRUIT_IO_CONTROL: Disabled
  ADAFRUIT_IO_KEY: ENTER YOUR ADAFRUIT_IO KEY HERE
  ADAFRUIT_IO_USERNAME: ENTER YOUR ADAFRUIT_IO USERNAME HERE
  FEEDNAME: ENTER YOUR ADAFRUIT_IO FEEDNAME THAT YOU WANT TO MONITOR HERE
Chromecast:
  Chromecast_Control: Enabled
  Chromecast_Devices:
    Device_Names:
    - Mini
    - "Tivi trước"
    IP_Address:
    - 192.168.1.11
    - 192.168.1.21
Conversation:
  Conversation_Control: Disabled
  answer:
    '1':
    - I am not the one you expect to be
    - Who do you think I am
    - What bothers you
    '2':
    - Nope i am forever alone
    - The whole world is my family
  question:
    '1':
    - Who are you
    '2':
    - Do you have a family
DIYHUE:
  DIYHUE_Control: Disabled
ESP:
  ESP_Control: Disabled
  IP: xxxxxxxxxxxx
  deviceid:
  - /Device1
  - /Device2
  - /Device3
  devicename:
  - Device 1
  - Device 2
  - Device 3
Google_Assistant:
  device_model_id: device_model_id
  project_id: project_id
Google_cloud_api_key: CHANGE_ME
Gpios:
  control: Enabled
  AIY_indicator:
  - 0
  assistant_indicators:
  - 0
  - 0
  ir:
  - 12
  picontrol:
  - 0
  pushbutton_trigger:
  - 17
  servo:
  - 0
  stopbutton_music_AIY_pushbutton:
  - 17
Home_Assistant:
  control: Enabled
  ratio: 70
  token: CHANGE_ME
  internal_url: http://CHANGE_ME:8123
  external_url: https://CHANGE_ME
IR:
  Codes:
  - 33738799
  - 33714319
  - 33720439
  - 33687799
  - 33735229
  - 33731149
  - 33708199
  - 33727069
  - 33702589
  - 33691879
  - 33744919
  - 33743389
  - 33730639
  Commands:
  - Time
  - Weather
  - Next
  - Prev
  - Mute
  - Stop
  - Story
  - Radio news
  - Music
  - VolUp
  - VolDown
  - Assistant
  - Play
  IR_Control: Enabled
  Music_list:
  - 'nhạc thiếu nhi'
  - 'cháu thương chú bộ đội'
  - 'liên khúc con heo đất'
  - 'nhạc thiếu nhi vai chú mang súng'
  - 'nhạc thiếu nhi quả gì'
  - 'nhạc thiếu nhi bé xuân mai'
  - 'nhạc thiếu nhi cả nhà thương nhau'
  - 'nhạc dân ca thiếu nhi'
  Story_list:
  - 'truyện cổ tích tích chu'
  - 'truyện cổ tích thánh gióng'
  - 'truyện kể cô bé quàng khăn đỏ'
  - 'truyện cổ tích việt nam'
  - 'truyện cổ tích tấm cám'
  - 'sự tích hoa mào gà'
  - 'sự tích quả dưa hấu'
  - 'truyện cây khế'
Language:
  Choice: vi-VN
  Language options:
  - en-US
  - vi-VN
MQTT:
  IP: Enter your MQTT IP ADDRESS here
  MQTT_Control: Disabled
  PSWRD: Enter your MQTT PASSWORD here
  TOPIC: ENTER your MQTT TOPIC here
  UNAME: Enter your MQTT USERNAME here
Notify_TTS:
  Notify_TTS_Control: Enabled
Pushbullet:
  Pushbullet_API_KEY: o.K3D6uw98nPz28eiCdRh3PgNYqYsg7a6I
  Pushbullet_Control: Enabled
Radio_stations:
  Radio_Control: 'Enabled'
  stationnames:
    - 'Bà Rịa Vũng Tàu'
    - 'kênh 1'
    - 'kênh 2'
    - 'kênh 3'
    - 'kênh 4'
    - 'vov2'
    - 'vov1'
    - 'vov3'
    - 'vov hà nội'
    - 'vov hồ chí minh'
  stationlinks:
    - 'http://113.163.216.23:1935/live/radio1.sdp_audio/playlist.m3u8'
    - 'https://strm.voh.com.vn/radio/channel2/chunklist_w591198153.m3u8'
    - 'https://strm.voh.com.vn/radio/channel1/chunklist_w1204836375.m3u8'
    - 'https://strm.voh.com.vn/radio/channel3/chunklist_w585709218.m3u8'
    - 'https://strm.voh.com.vn/live/channel5/chunklist_w257791589.m3u8'
    - 'http://stream2.mobiradio.vn/vovradio/vov2.stream/chunklist.m3u8'
    - 'http://stream2.mobiradio.vn/vovradio/vov1.stream/chunklist.m3u8'
    - 'http://stream2.mobiradio.vn/vovradio/vov3.stream/chunklist.m3u8'
    - 'http://stream2.mobiradio.vn/vovradio/vovgthn.stream/chunklist.m3u8'
    - 'http://stream2.mobiradio.vn/vovradio/vovgthcm.stream/chunklist.m3u8'
  stationradio:
    - 'Bà Rịa Vũng Tàu'
    - 'AM 610Khz'
    - 'FM 95.6 Mhz'
    - 'FM 99.9 Mhz'
    - 'FM 87.7 Mhz'
    - 'vov 2'
    - 'vov 1'
    - 'vov 3'
    - 'giao thông hà nội'
    - 'giao thông hồ chí minh'  
Raspberrypi_GPIO_Control:
  GPIO_Control: Disabled
  lightnames:
  - kitchen lights
  - bathroom lights
  - bedroom lights
Register_Device: False
Script:
  Script_Control: Disabled
  scriptcommand:
  - echo test >> /home/pi/test.txt
  scriptname:
  - Script test
Speechtotext:
  Google_Cloud_Speech:
    Cloud_Speech_Control: Disabled
    Google_Cloud_Speech_Credentials_Path: /home/pi/ViPi/src/google.json
Spotify:
  Spotify_Control: Disabled
  client_id: ENTER YOUR SPOTIFY CLIENT ID HERE
  client_secret: ENTER YOUR SPOTIFY CLIENT SECRET HERE
  username: ENTER YOUR SPOTIFY USERNAME HERE
Startup_voice: Disabled
Tasmota_devicelist:
  Tasmota_Control: Disabled
  friendly-names:
  - Desk Light
  - Table Light
  ipaddresses:
  - 192.168.1.36
  - 192.168.1.35
  portID:
  - '1'
  - '1'
TextToSpeech:
  Choice: gTTS
  Google_Cloud_TTS_Credentials_Path: ENTER THE PATH TO YOUR TTS CREDENTIALS FILE HERE
  Voice_Gender: Female
  Zalo_API: Vao_zalo.ai_dang_nhap_va_tao_key  
Wakewords:
  Custom_Wakeword: Enabled
  Ok_Google: Enabled
  Picovoice_wakeword_models:
  - /home/pi/ViPi/src/resources/picovoice_models/hey siri_raspberry-pi.ppn
  - /home/pi/ViPi/src/resources/picovoice_models/americano_raspberry-pi.ppn
  Wakeword_Engine: Picovoice
  sensitivities: 0.3
Weather:
  control: Disabled
  darksky_api: c457d056f60c2aa93fd47339aad294da
  ipfy_api: 128979ae3de728602f249354a85ac508
  lat_long:
  - 11.555358
  - 106.172483
Wemo:
  Wemo_Control: Disabled
  Wemo_Devices:
    Device_Names:
    - Enter wemo device 1 name here
    - Enter wemo device 1 name here
    IP_Address:
    - Enter wemo device 1 ip here
    - Enter wemo device 2 ip here
YouTube:
  YouTube_Control: Enabled
app_news_radio: Enabled
continue_conversation: False
ctr_led:
  type: R2M
